pygmentsCodeFences = true
pygmentsStyle = "tango"

enableMissingTranslationPlaceholders = true

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feeds/rss"

[taxonomies]
  topic = "topics"

[permalinks]
  blog = "/blog/articles/:slug/"

[languages]
  [languages.en]
    baseURL = "https://andreyfedoseev.com"
    contentDir = "content/en"
    staticDir = ["static/en"]
    languageName = "English"
    title = "Andrey Fedoseev"
    weight = 2
    [languages.en.params]
      author = "Andrey Fedoseev"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        title = "Archive"
        url = "/blog/archive/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "topics"
        name = "Topics"
        title = "Topics"
        url = "/topics/"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "RSS"
        title = "RSS"
        url = "/blog/feeds/rss.xml"
        weight = 3

  [languages.ru]
    baseURL = "https://andreyfedoseev.ru"
    contentDir = "content/ru"
    staticDir = ["static/ru"]
    languageName = "Русский"
    title = "Андрей Федосеев"
    weight = 1
    [languages.ru.params]
      author = "Андрей Федосеев"
    [languages.ru.menu]
      [[languages.ru.menu.main]]
        identifier = "archive"
        name = "Архив"
        title = "Архив"
        url = "/blog/archive/"
        weight = 1
      [[languages.ru.menu.main]]
        identifier = "topics"
        name = "Темы"
        title = "Темы"
        url = "/topics/"
        weight = 2
      [[languages.ru.menu.main]]
        identifier = "rss"
        name = "RSS"
        title = "RSS"
        url = "/blog/feeds/rss.xml"
        weight = 3
      [[languages.ru.menu.main]]
        identifier = "telegram"
        name = "Telegram"
        title = "Telegram"
        url = "https://t.me/andreyfedoseev_ru"
        weight = 4
      [[languages.ru.menu.main]]
        identifier = "twitter"
        name = "Twitter"
        title = "Twitter"
        url = "https://twitter.com/a_fedoseev"
        weight = 5
