pygmentsCodeFences: true
pygmentsStyle: tango

enableMissingTranslationPlaceholders: true

defaultContentLanguage: en

markup:
  goldmark:
    renderer:
      unsafe: true

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feeds/rss"

taxonomies:
  topic: topics

permalinks:
  blog: "/blog/articles/:slug/"

languages:
  en:
    contentDir: "content/en"
    staticDir: ["static/en"]
    languageName: "English"
    title: "Andrey Fedoseev"
    weight: 2
    params:
      author: "Andrey Fedoseev"
    menu:
      main:
        - identifier: "archive"
          name: "Archive"
          title: "Archive"
          url: "/blog/archive/"
          weight: 1
        - identifier: "topics"
          name: "Topics"
          title: "Topics"
          url: "/topics/"
          weight: 2
        - identifier: "rss"
          name: "RSS"
          title: "RSS"
          url: "/blog/feeds/rss.xml"
          weight: 3
        - identifier: "twitter"
          name: "Twitter"
          title: "Twitter"
          url: "https://twitter.com/a_fedoseev"
          weight: 4

  ru:
    contentDir: "content/ru"
    staticDir: ["static/ru"]
    languageName: "Русский"
    title: "Андрей Федосеев"
    weight: 1
    params:
      author: "Андрей Федосеев"
    menu:
      main:
        - identifier: "archive"
          name: "Архив"
          title: "Архив"
          url: "/blog/archive/"
          weight: 1
        - identifier: "topics"
          name: "Темы"
          title: "Темы"
          url: "/topics/"
          weight: 2
        - identifier: "rss"
          name: "RSS"
          title: "RSS"
          url: "/blog/feeds/rss.xml"
          weight: 3
        - identifier: "telegram"
          name: "Telegram"
          title: "Telegram"
          url: "https://t.me/andreyfedoseev_ru"
          weight: 4
        - identifier: "twitter"
          name: "Twitter"
          title: "Twitter"
          url: "https://twitter.com/a_fedoseev"
          weight: 5
